name: mattlean
favicon: null
layout_spectrum: 0.524654746055603
typography_spectrum: 0.78543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8cad8'
    - '#090400'
    - '#fdfaf5'
    - '#5e5b1d'
    - '#c67732'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
